In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier

In [2]:
df_categorical=pd.read_csv("files_for_lab/categorical.csv")
df_numerical=pd.read_csv("files_for_lab/numerical.csv")
df_target=pd.read_csv("files_for_lab/target.csv")

In [3]:
df_numerical.isna().sum()
df_target.isna().sum()

TARGET_B    0
TARGET_D    0
dtype: int64

In [4]:
df_numerical

,TCODE,AGE,INCOME,WEALTH1,HIT,MALEMILI,MALEVET,VIETVETS,WWIIVETS,LOCALGOV,...,CARDGIFT,MINRAMNT,MAXRAMNT,LASTGIFT,TIMELAG,AVGGIFT,CONTROLN,HPHONE_D,RFA_2F,CLUSTER2
0,0,60.000000,5,9,0,0,39,34,18,10,...,14,5.0,12.0,10.0,4,7.741935,95515,0,4,39
1,1,46.000000,6,9,16,0,15,55,11,6,...,1,10.0,25.0,25.0,18,15.666667,148535,0,2,1
2,1,61.611649,3,1,2,0,20,29,33,6,...,14,2.0,16.0,5.0,12,7.481481,15078,1,4,60
3,0,70.000000,1,4,2,0,23,14,31,3,...,7,2.0,11.0,10.0,9,6.812500,172556,1,4,41
4,0,78.000000,3,2,60,1,28,9,53,26,...,8,3.0,15.0,15.0,14,6.864865,7112,1,2,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,1,61.611649,5,9,0,14,36,47,11,7,...,0,25.0,25.0,25.0,9,25.000000,184568,0,1,12
95408,1,48.000000,7,9,1,0,31,43,19,4,...,0,20.0,20.0,20.0,9,20.000000,122706,1,1,2
95409,1,60.000000,5,9,0,0,18,46,20,7,...,4,3.0,10.0,10.0,3,8.285714,189641,1,3,34
95410,0,58.000000,7,9,0,0,28,35,20,9,...,18,5.0,21.0,18.0,4,12.146341,4693,1,4,11
95411,2,80.000000,5,8,3,1,33,22,27,8,...,11,10.0,201.0,100.0,6,96.794872,185114,1,1,12

In [5]:
df_categorical.dtypes

STATE           object
CLUSTER          int64
HOMEOWNR        object
GENDER          object
DATASRCE         int64
RFA_2R          object
RFA_2A          object
GEOCODE2        object
DOMAIN_A        object
DOMAIN_B         int64
ODATEW_YR        int64
ODATEW_MM        int64
DOB_YR           int64
DOB_MM           int64
MINRDATE_YR      int64
MINRDATE_MM      int64
MAXRDATE_YR      int64
MAXRDATE_MM      int64
LASTDATE_YR      int64
LASTDATE_MM      int64
FIRSTDATE_YR     int64
FIRSTDATE_MM     int64
dtype: object

In [6]:

df_categorical.shape

(95412, 22)

In [7]:
categorical_columns = ["STATE","HOMEOWNR","GENDER","RFA_2R","RFA_2A","GEOCODE2","DOMAIN_A"]

In [10]:
df_categorical_encoded = pd.DataFrame()
for col in categorical_columns:
    encoded = pd.get_dummies(df_categorical[col])
    df_categorical_encoded = pd.concat([df_categorical_encoded, encoded], axis=1)

In [12]:
y= df_target.drop(["TARGET_D"],axis=1)

In [13]:
x = pd.concat([df_numerical,df_categorical_encoded], axis=1)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [17]:
smote = SMOTE()
X_train_bal,y_train_bal=smote.fit_resample(X_train,y_train)

In [22]:
rg = RandomForestClass(max_depth=8, random_state=42, n_jobs=-1)
rg.fit(X_train_bal, y_train_bal)

NameError: name 'RandomForestRegressor' is not defined